{
    "name": "School Management",
    "version": "16.0",
    "application": True,
    "depends": ["base", "mail", "web"],
    "data": [
        'security/ir.model.access.csv',
        # 'template/template.xml',
        'data/sequence.xml',
        'views/student_information.xml',
        'views/student_model.xml',
        'views/school_class.xml',
        'views/teacher_information.xml',
        'views/school_information.xml',
        'views/parent_information.xml',
        'views/school_menus.xml',
    ],
    "installable": True,
    "license" : "LGPL-3",
}
